"""Ensure the committed tool inventory doc matches the live registry and package config.

If this test fails, someone changed tool registration or package membership without
regenerating the inventory. Run:

    python3 scripts/regenerate_tool_inventory.py
"""

from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = ROOT / "docs" / "TOOL_INVENTORY.md"
SCRIPT_PATH = ROOT / "scripts" / "regenerate_tool_inventory.py"


def _load_generator_module():
    spec = spec_from_file_location("regenerate_tool_inventory", SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to load generator module from {SCRIPT_PATH}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_tool_inventory_matches_generator_output():
    module = _load_generator_module()
    generated = module.build_inventory_markdown()
    committed = DOC_PATH.read_text(encoding="utf-8")
    assert committed == generated, (
        "docs/TOOL_INVENTORY.md is stale. Regenerate with "
        "`python3 scripts/regenerate_tool_inventory.py`."
    )


def test_tool_inventory_has_generation_banner():
    content = DOC_PATH.read_text(encoding="utf-8")
    assert "AUTO-GENERATED by `scripts/regenerate_tool_inventory.py`" in content
