"""Regenerate src/servicenow_mcp/tools/_module_index.py from the current
@register_tool decorators in tools/*.py.

Run this whenever a tool is added, removed, or moved between modules. A CI
test fails if the committed file drifts from the AST scan, so you won't
forget — but the error message points here.

Usage: python scripts/regenerate_tool_module_index.py
"""

from pathlib import Path

from servicenow_mcp.utils.registry import _build_tool_module_index


def main() -> None:
    idx = _build_tool_module_index()
    if not idx:
        raise SystemExit("AST scan returned no tools — check servicenow_mcp.tools package path.")

    items = sorted(idx.items())
    lines = [f'    "{k}": "{v}",' for k, v in items]
    content = (
        '"""Static tool_name → module_name map for lazy discovery.\n\n'
        "AUTO-GENERATED by scripts/regenerate_tool_module_index.py. Do not edit by hand.\n"
        "A CI test verifies this file matches the live AST scan of the tools/ package.\n"
        '"""\n\n'
        "TOOL_MODULE_INDEX = {\n" + "\n".join(lines) + "\n}\n"
    )

    target = (
        Path(__file__).resolve().parents[1]
        / "src"
        / "servicenow_mcp"
        / "tools"
        / "_module_index.py"
    )
    target.write_text(content, encoding="utf-8")
    print(f"Wrote {len(idx)} entries → {target}")


if __name__ == "__main__":
    main()
